version: '3'
services:
  proxyC:
    image: jwilder/nginx-proxy
    container_name: proxyC
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true
    networks:
      - local_containers      
  findex:
    image: richarvey/nginx-php-fpm:2.1.2
    container_name: findex
    dns:
      - 8.8.8.8    
    volumes:
      - ../.:/var/www/html
      - ./default.conf:/etc/nginx/sites-available/default.conf
    env_file:
      - .env
    environment:
      - SKIP_COMPOSER=1
      - VIRTUAL_HOST=findex.test
    networks:
      - local_containers
    restart: always
    command: bash -c 'apk add --update nodejs npm && cp .env.example .env && composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_LICENSE_KEY} && composer install && php artisan key:generate && npm install && npm run build && php artisan nova:publish && /start.sh'
    depends_on:
      - proxyC
networks:
  local_containers:
    name: local_containers